### ISSUE TITLE
Can you help me??

### ISSUE THREAD

**Issue by VinAppFun** [xissy/node-mecab-ffi#14]
**It runs smoothly local... I'm trying to run a project on Heroku. but its giving an error:**

`2016-08-06T04:39:57.166302+00:00 app[web.1]: Error: ENOENT: no such file or directory, open 'libmecab.so'
2016-08-06T04:39:57.166302+00:00 app[web.1]:   at Error (native)
2016-08-06T04:39:57.166303+00:00 app[web.1]:   at Object.fs.openSync (fs.js:584:18)
2016-08-06T04:39:57.166304+00:00 app[web.1]:   at fs.readFileSync (fs.js:431:33)
2016-08-06T04:39:57.166304+00:00 app[web.1]:   at new DynamicLibrary (/app/node_modules/ffi/lib/dynamic_library.js:67:21)
2016-08-06T04:39:57.166306+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/mecab-ffi/lib/index.coffee:19:16)
2016-08-06T04:39:57.166305+00:00 app[web.1]:   at Object.Library (/app/node_modules/ffi/lib/library.js:45:12)
2016-08-06T04:39:57.166306+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/mecab-ffi/lib/index.coffee:1:1)
2016-08-06T04:39:57.166307+00:00 app[web.1]:   at Module._compile (module.js:413:34)
2016-08-06T04:39:57.166308+00:00 app[web.1]:   at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
2016-08-06T04:39:57.166309+00:00 app[web.1]:   at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
2016-08-06T04:39:57.166310+00:00 app[web.1]:   at Function.Module._load (module.js:314:12)
2016-08-06T04:39:57.166310+00:00 app[web.1]:   at Module.require (module.js:367:17)
2016-08-06T04:39:57.166311+00:00 app[web.1]:   at require (internal/module.js:16:19)
2016-08-06T04:39:57.166311+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/mecab-ffi/index.js:8:18)
2016-08-06T04:39:57.166312+00:00 app[web.1]:   at Module._compile (module.js:413:34)
2016-08-06T04:39:57.166313+00:00 app[web.1]:   at Object.Module._extensions..js (module.js:422:10)
2016-08-06T04:39:57.166313+00:00 app[web.1]:   at Module.load (module.js:357:32)
2016-08-06T04:39:57.166314+00:00 app[web.1]:   at Function.Module._load (module.js:314:12)
2016-08-06T04:39:57.166314+00:00 app[web.1]:   at Module.require (module.js:367:17)
2016-08-06T04:39:57.166315+00:00 app[web.1]:   at require (internal/module.js:16:19)
2016-08-06T04:39:57.166315+00:00 app[web.1]:   at Object.<anonymous> (/app/app.js:2:13)
2016-08-06T04:39:57.166316+00:00 app[web.1]:   at Module._compile (module.js:413:34)
2016-08-06T04:39:57.166316+00:00 app[web.1]:   at Object.Module._extensions..js (module.js:422:10)
2016-08-06T04:39:57.166317+00:00 app[web.1]:   at Module.load (module.js:357:32)
2016-08-06T04:39:57.166317+00:00 app[web.1]:   at Function.Module._load (module.js:314:12)
2016-08-06T04:39:57.166318+00:00 app[web.1]:   at Function.Module.runMain (module.js:447:10)
2016-08-06T04:39:57.166319+00:00 app[web.1]:   at startup (node.js:142:18)
2016-08-06T04:39:57.166319+00:00 app[web.1]:   at node.js:939:3
2016-08-06T04:39:57.166320+00:00 app[web.1]: 
2016-08-06T04:39:57.239888+00:00 heroku[web.1]: State changed from starting to crashed
2016-08-06T04:39:57.227539+00:00 heroku[web.1]: Process exited with status 1
2016-08-06T04:40:18.314005+00:00 heroku[web.1]: State changed from crashed to starting
2016-08-06T04:40:19.506193+00:00 heroku[web.1]: Starting process with command`node app.js`
2016-08-06T04:40:21.151466+00:00 app[web.1]: fs.js:584
2016-08-06T04:40:21.151484+00:00 app[web.1]:   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
2016-08-06T04:40:21.151485+00:00 app[web.1]:                  ^
2016-08-06T04:40:21.151485+00:00 app[web.1]: 
2016-08-06T04:40:21.151486+00:00 app[web.1]: Error: ENOENT: no such file or directory, open 'libmecab.so'
2016-08-06T04:40:21.151487+00:00 app[web.1]:   at Error (native)
2016-08-06T04:40:21.151488+00:00 app[web.1]:   at Object.fs.openSync (fs.js:584:18)
2016-08-06T04:40:21.151489+00:00 app[web.1]:   at new DynamicLibrary (/app/node_modules/ffi/lib/dynamic_library.js:67:21)
2016-08-06T04:40:21.151488+00:00 app[web.1]:   at fs.readFileSync (fs.js:431:33)
2016-08-06T04:40:21.151490+00:00 app[web.1]:   at Object.Library (/app/node_modules/ffi/lib/library.js:45:12)
2016-08-06T04:40:21.151490+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/mecab-ffi/lib/index.coffee:19:16)
2016-08-06T04:40:21.151491+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/mecab-ffi/lib/index.coffee:1:1)
2016-08-06T04:40:21.151492+00:00 app[web.1]:   at Module._compile (module.js:413:34)
2016-08-06T04:40:21.151493+00:00 app[web.1]:   at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
2016-08-06T04:40:21.151494+00:00 app[web.1]:   at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
2016-08-06T04:40:21.151494+00:00 app[web.1]:   at Function.Module._load (module.js:314:12)
2016-08-06T04:40:21.151495+00:00 app[web.1]:   at Module.require (module.js:367:17)
2016-08-06T04:40:21.151496+00:00 app[web.1]:   at require (internal/module.js:16:19)
2016-08-06T04:40:21.151496+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/mecab-ffi/index.js:8:18)
2016-08-06T04:40:21.151497+00:00 app[web.1]:   at Module._compile (module.js:413:34)
2016-08-06T04:40:21.151498+00:00 app[web.1]:   at Object.Module._extensions..js (module.js:422:10)
2016-08-06T04:40:21.151498+00:00 app[web.1]:   at Module.load (module.js:357:32)
2016-08-06T04:40:21.151499+00:00 app[web.1]:   at Function.Module._load (module.js:314:12)
2016-08-06T04:40:21.151500+00:00 app[web.1]:   at Module.require (module.js:367:17)
2016-08-06T04:40:21.151500+00:00 app[web.1]:   at require (internal/module.js:16:19)
2016-08-06T04:40:21.151501+00:00 app[web.1]:   at Object.<anonymous> (/app/app.js:2:13)
2016-08-06T04:40:21.151502+00:00 app[web.1]:   at Module._compile (module.js:413:34)
2016-08-06T04:40:21.151503+00:00 app[web.1]:   at Module.load (module.js:357:32)
2016-08-06T04:40:21.151503+00:00 app[web.1]:   at Function.Module._load (module.js:314:12)
2016-08-06T04:40:21.151502+00:00 app[web.1]:   at Object.Module._extensions..js (module.js:422:10)
2016-08-06T04:40:21.151504+00:00 app[web.1]:   at Function.Module.runMain (module.js:447:10)
2016-08-06T04:40:21.151505+00:00 app[web.1]:   at startup (node.js:142:18)
2016-08-06T04:40:21.151505+00:00 app[web.1]:   at node.js:939:3
2016-08-06T04:40:21.151506+00:00 app[web.1]: 
2016-08-06T04:40:21.202024+00:00 heroku[web.1]: Process exited with status 1
2016-08-06T04:40:21.210439+00:00 heroku[web.1]: State changed from starting to crashed
`

**Comment by handrake** [comment]
It appears 'libmecab.so' cannot be found on your path.
