### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by LeeKyungMoon** [xissy/node-mecab-ffi#4]
I think I succeed in installing mecab & mecab-dic.

Please tell me if it is an error, when i installed mecab-dic, I got this message
: make[1]: Nothing to be done for `install-exec-am'.
 ./install-sh -c -d '/usr/local/lib/mecab/dic/mecab-ko-dic'
 /usr/bin/install -c -m 644 model.bin matrix.bin char.bin sys.dic unk.dic left-id.def right-id.def rewrite.def pos-id.def dicrc '/usr/local/lib/mecab/dic/mecab-ko-dic'

And then I run mecab.js 
:console.log('mecab.js');
require('coffee-script');
require('coffee-script/register');
var mecab = require('mecab-ffi');
//coffee.register();
mecab.parse('test input string', function(err, result) {
	console.log(result);
});

But I got an error message : 
/Users/LeeKyungMoon/Desktop/NodeJS/node_modules/mecab-ffi/lib/index.coffee:39
    throw new Error("Failed to create a new model - " + errorString);
          ^
Error: Failed to create a new model - param.cpp(69) [ifs] no such file or directory: /usr/local/lib/mecab/dic/ipadic/dicrc
  at Object.<anonymous> (/Users/LeeKyungMoon/Desktop/NodeJS/node_modules/mecab-ffi/lib/index.coffee:36:20)
  at Object.<anonymous> (/Users/LeeKyungMoon/Desktop/NodeJS/node_modules/mecab-ffi/lib/index.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/LeeKyungMoon/Desktop/NodeJS/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/LeeKyungMoon/Desktop/NodeJS/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/LeeKyungMoon/Desktop/NodeJS/node_modules/mecab-ffi/index.js:3:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/LeeKyungMoon/Desktop/NodeJS/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/LeeKyungMoon/Desktop/NodeJS/mecab.js:4:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

I am feeling crazy... Please Help me ㅜㅜ

**Comment by wodory** [comment]
You should modify the rc file to specify location of a Korean dictionary file. 
If you don't have Korean or other Dictionary, just install it. (Refer to https://bitbucket.org/eunjeon/mecab-ko)

The rc file is as below
```
/usr/local/etc/mecabrc
```

And the file contents is as below:
```
;
; Configuration file of MeCab
;
; $Id: mecabrc.in,v 1.3 2006/05/29 15:36:08 taku-ku Exp $;
;

; dicdir =  /usr/local/lib/mecab/dic/ipadic
dicdir =  /usr/local/lib/mecab/dic/mecab-ko-dic

; userdic = /home/foo/bar/user.dic

; output-format-type = wakati
; input-buffer-size = 8192

; node-format = %m\n
; bos-format = %S\n
; eos-format = EOS\n
```
